# Generated by Django 4.0 on 2022-01-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.TextField()),
                ('Cost_per_Item', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Stock_quantity', models.DecimalField(decimal_places=6, max_digits=6)),
                ('Volume', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
    ]
