# Generated by Django 4.0 on 2022-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_item_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Cost_per_Item',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='Stock_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='Volume',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=19, null=True),
        ),
    ]
