# Generated by Django 4.0 on 2022-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_item_cost_per_item_alter_item_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
