# Generated by Django 4.0 on 2022-01-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Cost_per_Item',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='Stock_quantity',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='Volume',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
